### ISSUE TITLE
Update Readme to include the required version of Java

### ISSUE THREAD

**Issue by abhaseen** [NesaByte/Bapples#1]
If a person is running a version of the JVE that is under v. 58.0, the .jar file will not work. This is important to note in a readme file so that users will be able to run this from the get-go.

Lines 13-16 are redundant code - it's never used in the program.

Semantics: --v is usually not an argument format you'll see, you may want to consider using -v, --version is good.

Line 125, line 132: Using magic numbers. Where does 999 come from?

Line 428, 440, 450, 546, 558, 568, 590, 606: Redundant `.toString()` method.

**Comment by NesaByte** [comment]
Thank you Andre. I will take a look at it, ASAP.
