### ISSUE TITLE
Lab 4 issue

### ISSUE THREAD

**Issue by eunbeek** [NesaByte/Bapples#14]
Hi,

If possible, Can I implement "ignore url" feature for Lab 4? 
I will let you know how it changed soon.

Thanks!

**Comment by NesaByte** [comment]
Hey there. Of course, have a go at it. Thank you and good luck!

**Comment by eunbeek** [comment]
Good morning!
I completed editing the code, and pull the request. 
Please check these changes and if you have a good suggestion or questions, I really welcome from your response. 

Thanks!

**Comment by NesaByte** [comment]
Hi Eunbeek, sorry I wasn't able to reply quickly. Thank you so much for your interest in my project and for the wait, I will be checking it right now!
