### ISSUE TITLE
Add Terminal Colours 

### ISSUE THREAD

**Issue by rjayroso** [NesaByte/Bapples#9]
Hi Nesa, I would like to add terminal colour output to your Bapples link checker. Additionally, I would like to add some screen shots and or gifs to your read me that features the new coloured terminal text.

**Comment by rjayroso** [comment]
I added terminal colour output, added a help message argument, and I also reduced the code length by making duplicate code into a single method. Unfortunately windows command prompt does not support coloured text (only black and white) so I am unable to get the coloured screen shots.

**Comment by NesaByte** [comment]
Thanks, will review it now.
